#!/usr/bin/env bash

#this must be run from the root directory of the repo
#this assumes you're setup to build rpms in ~/rpmbuild/

#make this match the spec!!!
version=0.0.1

mkdir /tmp/slurmmon-$version
rsync -av --exclude /slurmmon-$version.tar.bz2 --exclude /*.rpm --exclude /.git/ ./ /tmp/slurmmon-$version/
tar --owner root --group root --numeric-owner -cjvf slurmmon-$version.tar.bz2 -C /tmp slurmmon-$version
rm -fr /tmp/slurmmon-$version
/bin/cp -af slurmmon-$version.tar.bz2 ~/rpmbuild/SOURCES/

rpmbuild -ba --target=noarch slurmmon.spec

/bin/cp -af ~/rpmbuild/RPMS/noarch/slurmmon* .
/bin/cp -af ~/rpmbuild/SRPMS/slurmmon* .
